[build]
  publish = "dist"
  command = "npm run build"

# Environment variables for better build process
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Headers for PDF files - ensure proper content type and allow downloads
[[headers]]
  for = "/cv/*"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "inline; filename=cv.pdf"
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "inline; filename=document.pdf"
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"

# Ensure static files are served correctly
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for all static files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Specific redirects to handle PDF files correctly
[[redirects]]
  from = "/cv/my-cv.pdf"
  to = "/cv/my-cv.pdf"
  status = 200
  force = true

# Main SPA redirect - must be last and should not catch PDF files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}
  force = false